import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { Inter } from 'next/font/google';

import Providers from './providers';

import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import '@rainbow-me/rainbowkit/styles.css';

import './globals.css';

export const metadata: Metadata = {
  title: 'Stakeverses',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = headers().get('cookie');

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
