import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { Inter } from 'next/font/google';

import Providers from './providers';
import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';
import '@rainbow-me/rainbowkit/styles.css';
import 'aos/dist/aos.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Stakeverses',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.ico',
  }
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = headers().get('cookie');

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} overflow-x-hidden`}>
        <Providers cookie={cookie}>
          <Header />
          <main className="relative px-[20px] 2xl:px-[130px] xl:px-[100px] lg:px-[70px] text-black dark:text-white">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
